stages:
- test

run-tests:
  stage: test
  image: python:3.12
  variables:
    PIP_ROOT_USER_ACTION: ignore
  before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt .
  script:
  - ruff format --check
  - ruff check
  - pytest -v
